services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_main
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Istanbul
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secret
      - WEBHOOK_URL=https://untroublesome-unslatted-lori.ngrok-free.dev
      - EXECUTIONS_PROCESS=main
    
   
    volumes:
      - ./n8n_data:/home/node/.n8n

    
    extra_hosts:
      - "host.docker.internal:host-gateway"